version : 0.2

env:
  parameter-store:
    DOCKER_USERNAME : /app/docker/username
    DOCKER_PASSWORD : /app/docker/password
    DOCKER_URL : /app/docekr-registry/url

phases: 
  install:
    runtime-versions: 
      python : 3.10
    
  pre_build:
    commands:
      - echo "Installing required files..."
      - pip install -r requirements.txt
      - echo "Build stage complete!!"
        
  build:
    commands:
      - echo "Building the Docker image..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_URL"
      - docker build -t "$DOCKER_URL/pookie-flask:latest" .
      - docker push "$DOCKER_URL/pookie-flask:latest"
  post_build:
    commands:
      - echo "Build completed!!!"